# Book settings
title: Mood Anxiety
author: Chirag Limbachia
copyright: "2020"
logo: "logo.png"

execute:
  exclude_patterns:
    - "00-initial-ROIs/*"
    - "05-LOO-mod1-vs-mod2*"
    - "correlation_and_VIFs*"
    - "ROI_masks/MAX_ROIs_final_gm"
    - "03-MSS/*"

latex:
  latex_documents:
    targetname: book.tex
