# Book settings
title: Mood Anxiety
author: Chirag Limbachia
copyright: "2020"
logo: "logo.png"

execute:
  exclude_patterns:
    - "00-initial-ROIs/*"
    - "01-final-ROIs/03-*"
    - "05-LOO-mod1-vs-mod2*"
    - "correlation_and_VIFs*"
    - "ROI_masks/MAX_ROIs_final_gm"
    - "03-MSS/*"

latex:
  latex_documents:
    targetname: book.tex

###########################################################################
# HTML-specific settings
html:
  home_page_in_navbar: false
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true

##########################################################################
# Launch button settings
repository:
  url: https://github.com/LCE-UMD/mood-anxiety
latex:
  latex_engine: "xelatex"
  latex_documents:
    targetname: book.tex
